In [4]:
! pip install numpy
! pip install --upgrade pip



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
  Using cached pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-25.3-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.2
    Uninstalling pip-25.2:
      Successfully uninstalled pip-25.2


In [5]:
import numpy as np

# Input matrix
A = np.array([[1, 0],
              [0, 1],
              [1, 1]], dtype=float)

# Compute A^T A
ATA = A.T @ A

# Eigen decomposition
eigen_value, v = np.linalg.eig(ATA)

# Sort in descending order
idx = np.argsort(-eigen_value)
eigen_value = eigen_value[idx]
v = v[:, idx]

# Singular values
singular_values = np.sqrt(eigen_value)

# Left singular vectors U = A * v / σ
U = np.zeros((A.shape[0], len(singular_values)))

for i in range(len(singular_values)):
    U[:, i] = (A @ v[:, i]) / singular_values[i]

# Normalize U columns
U = U / np.linalg.norm(U, axis=0)

# Construct Σ (2×2 because rank = 2)
Sigma = np.diag(singular_values)

# Reconstruct A
A_reconstruct = U @ Sigma @ v.T

print("A =\n", A)
print("\nA^T A =\n", ATA)
print("\nEigenvalues of A^T A:\n", eigen_value)
print("\nSingular values:\n", singular_values)
print("\nRight singular vectors (V):\n", v)
print("\nLeft singular vectors (U):\n", U)
print("\nΣ (Sigma):\n", Sigma)
print("\nReconstructed A =\n", A_reconstruct)


A =
 [[1. 0.]
 [0. 1.]
 [1. 1.]]

A^T A =
 [[2. 1.]
 [1. 2.]]

Eigenvalues of A^T A:
 [3. 1.]

Singular values:
 [1.73205081 1.        ]

Right singular vectors (V):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Left singular vectors (U):
 [[ 0.40824829 -0.70710678]
 [ 0.40824829  0.70710678]
 [ 0.81649658  0.        ]]

Σ (Sigma):
 [[1.73205081 0.        ]
 [0.         1.        ]]

Reconstructed A =
 [[ 1.00000000e+00 -1.00875766e-16]
 [-1.00875766e-16  1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00]]
